# This is a basic workflow to help you get started with Actions

name: password

# Controls when the workflow will run
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Print Password
        env: 
          MY_PASSWORD: ${{PASSWORD}} 
        run: echo $MY_PASSWORD
